name: latest
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
permissions: {}
jobs:
  latest:
    if: github.event.repository.fork == false
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - id: latest
        run: |
          echo "updates=$(./check-latest-versions.sh)" >> $GITHUB_OUTPUT
          if [ -n "$(git status --porcelain)" ]; then
            echo "pr=true" >> $GITHUB_OUTPUT
          fi
      - uses: peter-evans/create-pull-request@v8
        if: steps.latest.outputs.pr
        with:
          commit-message: ${{ steps.latest.outputs.updates }}
          title: ${{ steps.latest.outputs.updates }}
          delete-branch: true
